#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun  3 15:57:48 2018

@author: parkershankin-clarke
"""

import tensorflow as tf


#Create a Tensor Board
a = tf.constant(5,name = "input_a")
b = tf.constant(3,name = "input_b")
c = tf.multiply(a,b,name = "multiply_by_c")
d = tf.add(a,b, name = "add_d")
e = tf.add(c,d,name="add_e")
sess = tf.Session()
output = sess.run(e)
writer = tf.summary.FileWriter('./my_graph',sess.graph)
writer.close()
sess.close()

#This is what should be typed into the terminal in order to give the website on which the tensor board is located.
#tensorboard --logdir = my_graph/
#This is the URL to the video 